id: camera_offline_notifier
blueprint:
  name: Camera Offline Notifier BETA (v0.0.2)
  homeassistant:
    min_version: "2024.6.0"
  description: Sends a push notification to your mobile device when one or more selected cameras go offline (become 'unavailable').
  
  domain: automation
  
  source_url: https://github.com/thenextbutton/home_assistant/blob/main/blueprints/camera_offline/camera_offline_beta.yaml
  input:
    camera_selection:
      name: Camera Selection
      description: <br>Select Cameras to be monitored for offline notifications<br></br>
      icon: mdi:cctv
      collapsed: false
      input:
        cameras:
          name: Cameras to Monitor
          description: Select one or more camera entities that you want to monitor for offline status.
          selector:
            entity:
              filter:
                domain: camera
              multiple: true

    notification_actions:
      name: Notification Actions
      description: <br>Configure the notification to the device.<br></br>
      icon: mdi:cellphone
      collapsed: true
      input:
        notify_devices:
          name: Device(s) to Notify
          description: Select the mobile device (running the Home Assistant app) to send the offline notification to.
          selector:
            device:
              filter:
                integration: mobile_app
              multiple: false
        offline_duration:
          name: Offline Duration
          description: How long the camera must be offline (unavailable) before triggering the notification.
          default: { hours: 0, minutes: 2, seconds: 0 }
          selector:
            duration:
              enable_day: false
              enable_millisecond: false
        notification_title:
          name: Notification title
          description: what you want the title to be
          default: "🚨 Camera Offline Alert 🚨"
          selector:
            text:
              multiline: false
              type: text
              multiple: false
        notification_message:
          name: Notification message
          description: what you want the message to be
          default: >
            {% set total_seconds = (now() - trigger.to_state.last_changed).total_seconds() | int %}
            {% set seconds = total_seconds % 60 %}
            {% set minutes = (total_seconds // 60) % 60 %}
            {% set hours = total_seconds // 3600 %}
            Camera '{{ trigger.to_state.attributes.friendly_name }}' ({{ trigger.entity_id }}) is offline and has been for {{ "%02d:%02d:%02d" | format(hours, minutes, seconds) }}!
          selector:
            text:
              multiline: true
              type: text
              multiple: false
        notification_critical:
          name: Notification critical
          description: do you want this to be critical?
          default: false
          selector:
            boolean:

mode: queued
triggers:
  - trigger: state
    entity_id: !input cameras
    to: "unavailable"
    for: !input offline_duration

action:
  - variables:
      notification_title: !input notification_title
      notification_message: !input notification_message
      notification_critical: !input notification_critical
      notify_devices: !input notify_devices

  - alias: "Send a notification to the device"
    sequence:
      - device_id: !input notify_devices
        domain: mobile_app
        type: notify
        title: !input notification_title
        message: !input notification_message
        data: >
          {% if notification_critical %}
          {% set critical_data = {
              'ttl': 0,
              'priority': 'high',
              'push': {
                  'sound': {
                      'name': 'default',
                      'critical': 1,
                      'volume': 1.0
                  }
              }
          } %}
          {{ critical_data }}
          {% else %}
          {}
          {% endif %}
