id: plex_webhook_handler_beta
blueprint:
  name: Plex Webhook Handler BETA (v0.1.3)
  homeassistant:
    min_version: "2024.6.0"
  description: "Handles Plex Webhook Events.<br></br>A Plex Client name is only required for Movie, Music and TV Show actions."

  domain: automation
  
  source_url: https://github.com/thenextbutton/home_assistant/blob/main/blueprints/plex_webhook_handler/plex_webhook_beta.yaml
  
  input:
    webhook_id:
      name: Webhook ID
      description: "The webhook ID configured in your Plex Media Server."
      selector:
        text:
          multiline: false
          multiple: false
      default: ""
    local_only:
      name: Local Only
      description: "Only allow webhook requests from the local network."
      selector:
        boolean: {}
      default: true
    plex_client:
      name: Plex Client
      description: "The Plex client name to trigger actions for."
      selector:
        text:
          multiline: false
          multiple: false
      default: ""

    movie_actions:
      name: Movie Actions
      description: "<br>Actions to run for Movie Plex events.<br></br>"
      icon: mdi:movie
      collapsed: true
      input:
        movie_play_actions:
          name: Movie Play Actions
          description: "Actions to run when a movie starts or resumes."
          selector:
            action: {}
          default: []
        movie_resume_mimics_play:
          name: Movie Resume Mimics Play Actions
          description: "On RESUME mimic the Movie play actions."
          selector:
            boolean: {}
          default: false
        movie_resume_actions:
          name: Movie Resume Actions
          description: "Actions to run when a movie starts or resumes."
          selector:
            action: {}
          default: []
        movie_pause_actions:
          name: Movie Pause Actions
          description: "Actions to run when a movie is paused."
          selector:
            action: {}
          default: []
        movie_stop_actions:
          name: Movie Stop Actions
          description: "Actions to run when a movie stops."
          selector:
            action: {}
          default: []

    music_actions:
      name: Music Actions
      description: "<br>Actions to run for Music Plex events.<br></br>"
      icon: mdi:music
      collapsed: true
      input:
        track_play_actions:
          name: Music Play Actions
          description: "Actions to run when a track starts or resumes."
          selector:
            action: {}
          default: []
        track_resume_mimics_play:
          name: Music Resume Mimics Play Actions
          description: "On RESUME mimic the Music play actions."
          selector:
            boolean: {}
          default: false
        track_resume_actions:
          name: Music Resume Actions
          description: "Actions to run when a track starts or resumes."
          selector:
            action: {}
          default: []
        track_pause_actions:
          name: Music Pause Actions
          description: "Actions to run when a track is paused."
          selector:
            action: {}
          default: []
        track_stop_actions:
          name: Music Stop Actions
          description: "Actions to run when a track stops."
          selector:
            action: {}
          default: []

    television_actions:
      name: TV Show Actions
      description: "<br>Actions to run for TV Plex events.<br></br>"
      icon: mdi:television
      collapsed: true
      input:
        episode_play_actions:
          name: TV Show Play Actions
          description: "Actions to run when an episode starts or resumes."
          selector:
            action: {}
          default: []
        episode_resume_mimics_play:
          name: TV Show Resume Mimics Play Actions
          description: "On RESUME mimic the TV Show play actions."
          selector:
            boolean: {}
          default: false
        episode_resume_actions:
          name: TV Show Resume Actions
          description: "Actions to run when an episode starts or resumes."
          selector:
            action: {}
          default: []
        episode_pause_actions:
          name: TV Show Pause Actions
          description: "Actions to run when an episode is paused."
          selector:
            action: {}
          default: []
        episode_stop_actions:
          name: TV Show Stop Actions
          description: "Actions to run when an episode stops."
          selector:
            action: {}
          default: []

    server_actions:
      name: Server Owner Actions
      description: "<br>These events are sent only for the server owner/admin account and relate to events on the server in general.<br></br>"
      icon: mdi:database-cog
      collapsed: true
      input:
        admin_database_backup_actions:
          name: Admin Database Backup Actions
          description: "Actions to run when an admin database backup event occurs."
          selector:
            action: {}
          default: []
        admin_database_corruption_actions:
          name: Admin Database Corruption Actions
          description: "Actions to run when an admin database corruption event occurs."
          selector:
            action: {}
          default: []

    new_item_actions:
      name: NEW Content Actions
      description: "<br>Actions to run for NEW Plex content.<br></br>"
      icon: mdi:alert-decagram
      collapsed: true
      input:
        library_new_actions:
          name: New Library Item(s)
          description: "A new item is added to a library."
          selector:
            action: {}
          default: []

    automation_actions:
      name: Automation Actions
      description: "<br>These are options for how the automation should respond<br></br>"
      icon: mdi:cog
      collapsed: true
      input:
        automation_mode:
          name: Automation Mode
          description: "Mode controls how the automation responds to new webhook triggers during an active run."
          selector:
            select:
              mode: list
              multiple: false
              options:
                - label: Single
                  value: single
                - label: Restart (Default)
                  value: restart
                - label: Queued
                  value: queued
                - label: Parallel
                  value: parallel
          default: restart
        trace_count:
          name: Trace Count
          description: "Number of traces to keep. (Minimum 1, Maximum 20 - Default 5)<br>Can be useful to increase for debugging."
          selector:
            number:
              min: 1
              max: 20
              step: 1
              mode: box
          default: 5
mode: !input automation_mode
triggers:
  - trigger: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: !input local_only
    webhook_id: !input webhook_id
conditions: []
action:
  - variables:
      payload: "{{ trigger.data['payload'].decode('utf-8') | from_json }}"
      player_title: "{{ payload.Player.title if 'Player' in payload else None }}" #NEW
      plex_client: !input plex_client
      movie_resume_mimics_play: !input movie_resume_mimics_play
      track_resume_mimics_play: !input track_resume_mimics_play
      episode_resume_mimics_play: !input episode_resume_mimics_play
      trace_count: !input trace_count
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ payload.event == 'admin.database.backup' }}"
        sequence: !input admin_database_backup_actions

      - conditions:
          - condition: template
            value_template: "{{ payload.event == 'admin.database.corrupted' }}"
        sequence: !input admin_database_corruption_actions

      - conditions:
          - condition: template
            value_template: "{{ payload.event == 'library.new' }}"
        sequence: !input library_new_actions

      - conditions:
          - condition: template
            value_template:
              "{{ player_title.lower().strip() == plex_client.lower().strip()
              }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ payload.Metadata.type == 'movie' }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template:
                              "{{ payload.event == 'media.play' or (payload.event
                              == 'media.resume' and movie_resume_mimics_play) }}"
                        sequence: !input movie_play_actions
                      - conditions:
                          - condition: template
                            value_template:
                              "{{ payload.event == 'media.resume' and not movie_resume_mimics_play
                              }}"
                        sequence: !input movie_resume_actions
                      - conditions:
                          - condition: template
                            value_template: "{{ payload.event == 'media.pause' }}"
                        sequence: !input movie_pause_actions
                      - conditions:
                          - condition: template
                            value_template: "{{ payload.event == 'media.stop' }}"
                        sequence: !input movie_stop_actions
              - conditions:
                  - condition: template
                    value_template: "{{ payload.Metadata.type == 'track' }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template:
                              "{{ payload.event == 'media.play' or (payload.event
                              == 'media.resume' and track_resume_mimics_play)}}"
                        sequence: !input track_play_actions
                      - conditions:
                          - condition: template
                            value_template:
                              "{{ payload.event == 'media.resume' and not track_resume_mimics_play
                              }}"
                        sequence: !input track_resume_actions
                      - conditions:
                          - condition: template
                            value_template: "{{ payload.event == 'media.pause' }}"
                        sequence: !input track_pause_actions
                      - conditions:
                          - condition: template
                            value_template: "{{ payload.event == 'media.stop' }}"
                        sequence: !input track_stop_actions
              - conditions:
                  - condition: template
                    value_template: "{{ payload.Metadata.type == 'episode' }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template:
                              "{{ payload.event == 'media.play' or (payload.event
                              == 'media.resume' and episode_resume_mimics_play)}}"
                        sequence: !input episode_play_actions
                      - conditions:
                          - condition: template
                            value_template:
                              "{{ payload.event == 'media.resume' and not episode_resume_mimics_play
                              }}"
                        sequence: !input episode_resume_actions
                      - conditions:
                          - condition: template
                            value_template: "{{ payload.event == 'media.pause' }}"
                        sequence: !input episode_pause_actions
                      - conditions:
                          - condition: template
                            value_template: "{{ payload.event == 'media.stop' }}"
                        sequence: !input episode_stop_actions

trace:
  stored_traces: !input trace_count
